export default {
    mercury: `Mercury is the closest planet to the Sun. It is only 58 million km / 36 million mi or 0.39 AU away. Though it is the closest, it isn’t the hottest planet in the Solar System; Venus holds that titled.
Mercury is, however, the smallest planet out of the eight. It is slightly larger than our Moon but smaller than Ganymede – one of Jupiter’s moons. Mercury itself doesn’t have any moons. Being a terrestrial planet, Mercury has a high density, and it is primarily composed out of rock and iron ore. Its surface is heavily cratered, very similar to Earth’s Moon. 
Mercury orbits the Sun once every 87.97 Earth days, while one Mercurian day is equivalent to 59 Earth days. Surface temperatures range from – 173 to 427 degrees Celsius. The small planet has a diameter of 4.879 km / 3.032 mi.`,
    venus: `The second closest planet to the Sun. Venus is on average at a distance of 108 million km / 67 million mi or 0.72 AU away from the Sun. It is the hottest planet of the Solar system since its atmosphere keeps the temperatures almost consistently the same.
The temperatures are around 462 degrees Celsius – about four and a half times the amount of heat needed to evaporate water. Its diameter has been measured to be at 12.104 km / 7.521 mi. Venus has 90% the Earth’s surface area, and it orbits the Sun once every 225 days. One day on Venus is equivalent to 243 Earth days; thus, a day on Venus is longer than a year.
Its atmosphere is very thick, composed mainly out of carbon dioxide, nitrogen, and clouds of sulfuric acid. It doesn’t have any moons, and the planet, like Uranus, spins backward – retrograde rotation. It is a terrestrial planet, often considered Earth’s sister.`,
    earth: `The third closest planet to the Sun. Earth is at an average distance of 150 million km / 93 million mi or 1 AU away from the Sun. It only has one moon and several other smaller satellites.

Earth is the biggest terrestrial planet having a diameter of 12.760 km / 7.926 mi. Surface temperatures on Earth are around 14 degrees Celsius.
Around 70% of Earth’s surface is covered in water, while the atmosphere is made out of 78% nitrogen, 21% oxygen, and 1% other gases.`,
    mars: `The fourth terrestrial planet and closest celestial body to the Sun. Mars is 228 million km / 142 million mi or 1.52 AU distance away from the Sun.
Also known as the Red Planet due to its reddish hue primarily because of its iron oxide on its surface, Mars is very similar to Earth. It has two moons, Phobos and Deimos. Like Earth, it has volcanoes, valleys, deserts, and polar ice caps.  The rotational period and tilt are also very similar to Earth with one day lasting 24 hours and 37 minutes, while a year is equivalent to 687 Earth days.
The atmosphere is thin, while the surface temperatures are, on average, around -63 degrees Celsius. Mars has a diameter of 6.787 km / 4.217 mi. More than 40 spacecraft have been launched to Mars.`,
    jupiter: `The fifth and most massive planet of the Solar System. Jupiter is 778 million km / 484 million mi or 5.2 AU away from the Sun. It is 317 times more massive than Earth and 2.5 times larger than all the other planets combined.Jupiter is a gas giant; it is primarily composed of hydrogen, helium, and other gases. Its atmosphere is the most intense in the Solar System. Jupiter is a gas giant; it is primarily composed of hydrogen, helium, and other gases. Its atmosphere is the most intense in the Solar System.
Probably second only to Uranus in terms of wind speeds which can reach up to 100 m/s or even more. Jupiter has a diameter of 142.984 km / 88.846 mi. One year on Jupiter is the equivalent of 12 Earth years, while a day lasts only 9.8 hours. Temperatures are around -148 degrees Celsius. Jupiter has 79 moons while possibly more awaiting confirmation; it is only second to Saturn in terms of satellites.`,
    saturn: `The sixth planet from the Sun, and also a gas giant. Saturn is 1.4 billion km / 886 million mi or 9.5 AU distance away from the Sun. Seven ring systems surround it.
The gas giant has been recently crowned as the king of the moons since it has 82 confirmed satellites. Its atmosphere is made up of hydrogen, helium, and other gases. Saturn’s diameter has been estimated to be at around 120.500 km / 74.900 mi. A year on Saturn is the equivalent of 30 Earth years, while a day lasts 10.7 hours.
The average temperatures on Saturn are around -178 degrees Celsius. Saturn is probably the most recognizable planet of the Solar System.`,
    neptune: `The farthest planet, Neptune. It lies at around 4.5 billion km / 2.8 billion mi or 30.07 AU away from the Sun. Like Uranus, it is also an ice giant.
It has a series of faint planetary rings, around 14 confirmed moons, and it has the fastest wind speeds of any planet, reaching speeds of 2.160 km / 1.314 mi per hour.`,
};